name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - tcloud

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          # key: ${{ secrets.KEY }} # Your server's SSH private key
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.APP_PATH }} # Specify the path to your app directory on the server
            git pull
            npm install
            npm run build
            pm2 restart dota-admin # Replace with your PM2 service name
